#!/usr/bin/env python3
"""Generate Waypoint's offline Portuguese emoji catalog from pinned upstream data."""

from __future__ import annotations

import json
import pathlib
import re
import unicodedata
import urllib.request
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1]
EMOJI_METADATA_REVISION = "90b58c872095ada14aaf49af85e3d87ae84e10f6"
EMOJI_ORDERING_URL = (
    "https://raw.githubusercontent.com/googlefonts/emoji-metadata/"
    f"{EMOJI_METADATA_REVISION}/emoji_17_0_ordering.json"
)
CLDR_RELEASE = "release-48"
CLDR_BASE_URL = f"https://raw.githubusercontent.com/unicode-org/cldr/{CLDR_RELEASE}/common"
CLDR_ANNOTATION_URLS = (
    f"{CLDR_BASE_URL}/annotations/pt.xml",
    f"{CLDR_BASE_URL}/annotationsDerived/pt.xml",
)
OUTPUTS = (
    ROOT / "qml/data/EmojiCatalog.js",
    ROOT / "plugins/omarchy-waypoint/EmojiCatalog.js",
)

CATEGORY_METADATA = {
    "Smileys and emotions": ("rostos", "Rostos", "😀"),
    "People": ("pessoas", "Pessoas", "👋"),
    "Animals and nature": ("natureza", "Natureza", "🌿"),
    "Food and drink": ("comida", "Comida", "🍎"),
    "Travel and places": ("viagem", "Viagem", "🚗"),
    "Activities and events": ("atividades", "Atividades", "⚽"),
    "Objects": ("objetos", "Objetos", "💡"),
    "Symbols": ("simbolos", "Símbolos", "❤️"),
    "Flags": ("bandeiras", "Bandeiras", "🏳️"),
}


def fetch_text(url: str) -> str:
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def normalized_emoji(value: str) -> str:
    return value.replace("\ufe0f", "")


def normalized_search(value: str) -> str:
    decomposed = unicodedata.normalize("NFD", value.casefold())
    without_accents = "".join(character for character in decomposed if unicodedata.category(character) != "Mn")
    return re.sub(r"\s+", " ", without_accents).strip()


def parse_annotations() -> dict[str, dict[str, object]]:
    annotations: dict[str, dict[str, object]] = {}
    for url in CLDR_ANNOTATION_URLS:
        root = ET.fromstring(fetch_text(url))
        for element in root.findall("./annotations/annotation"):
            emoji = normalized_emoji(element.attrib["cp"])
            entry = annotations.setdefault(emoji, {"name": "", "keywords": []})
            text = element.text or ""
            if element.attrib.get("type") == "tts":
                entry["name"] = text
            else:
                entry["keywords"] = [part.strip() for part in text.split("|") if part.strip()]
    return annotations


def build_catalog() -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    ordering = json.loads(fetch_text(EMOJI_ORDERING_URL))
    annotations = parse_annotations()
    categories: list[dict[str, str]] = []
    items: list[dict[str, str]] = []

    for group in ordering:
        category_id, label, glyph = CATEGORY_METADATA[group["group"]]
        categories.append({"id": category_id, "label": label, "emoji": glyph})
        for raw_item in group["emoji"]:
            emoji = "".join(chr(codepoint) for codepoint in raw_item["base"])
            annotation = annotations.get(normalized_emoji(emoji), {})
            shortcodes = [code.strip(":").replace("-", " ") for code in raw_item["shortcodes"]]
            name = str(annotation.get("name") or (shortcodes[0] if shortcodes else emoji))
            keywords = [str(keyword) for keyword in annotation.get("keywords", [])]
            search = normalized_search(" ".join([name, *keywords, *shortcodes]))
            items.append({"emoji": emoji, "category": category_id, "name": name, "search": search})

    return categories, items


def javascript_source(categories: list[dict[str, str]], items: list[dict[str, str]]) -> str:
    categories_json = json.dumps(categories, ensure_ascii=False, separators=(",", ":"))
    items_json = json.dumps(items, ensure_ascii=False, separators=(",", ":"))
    return f'''// Generated by tools/generate_emoji_catalog.py. Do not edit.
// Emoji ordering: googlefonts/emoji-metadata {EMOJI_METADATA_REVISION} (Apache-2.0).
// Portuguese annotations: Unicode CLDR {CLDR_RELEASE} (Unicode-3.0).
.pragma library

var categories = {categories_json}
var items = {items_json}

function normalizeSearch(value) {{
    return String(value || "").toLocaleLowerCase().normalize("NFD")
        .replace(/[\\u0300-\\u036f]/g, "").replace(/\\s+/g, " ").trim()
}}

function filtered(category, query) {{
    const normalizedQuery = normalizeSearch(query)
    return items.filter(function(item) {{
        return (category === "" || item.category === category)
            && (normalizedQuery === "" || item.search.indexOf(normalizedQuery) !== -1)
    }})
}}
'''


def main() -> None:
    categories, items = build_catalog()
    source = javascript_source(categories, items)
    for output in OUTPUTS:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(source, encoding="utf-8")
    print(f"Generated {len(items)} emoji across {len(categories)} categories")


if __name__ == "__main__":
    main()
